#!/bin/bash
year=`date +%Y`
month=`date +%m`
day=`date +%d`
title="$year-$month-$day-$1.md"
echo '---' > "_posts/$title"
echo 'layout: post' >> "_posts/$title"
echo 'title: ""' >> "_posts/$title"
echo 'categories: ' >> "_posts/$title"
echo 'description: ' >> "_posts/$title"
echo 'key: ' >> "_posts/$title"
echo '---' >> "_posts/$title"
vim "_posts/$title"
